OFTUTIDeclarationUsageType: OFExportOnlyDeclaration
UTTypeConformsTo:
- public.comma-separated-values-text
UTTypeDescription: CSV (UTF-16)
UTTypeIdentifier: com.omnigroup.omnifocus2.export-filetype.comma-separated-values-unicode
UTTypeTagSpecification:
  public.filename-extension:
  - csv
